# Generated by Django 5.0.2 on 2024-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Makale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yazar", models.CharField(max_length=150)),
                ("baslık", models.CharField(max_length=120)),
                ("acıklama", models.CharField(max_length=200)),
                ("metin", models.TextField()),
                ("sehir", models.CharField(max_length=120)),
                ("yayımlanma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("güncellenme_tarihi", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
