# Generated by Django 5.0.2 on 2024-02-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Makale_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yazar", models.CharField(max_length=150)),
                ("baslik", models.CharField(max_length=120)),
                ("aciklama", models.CharField(max_length=200)),
                ("metin", models.TextField()),
                ("sehir", models.CharField(max_length=120)),
                ("yayimlanma_tarihi", models.DateTimeField()),
                ("güncellenme_tarihi", models.DateTimeField(auto_now=True)),
                ("aktif", models.BooleanField(default=True)),
                ("yaratilma_tarihi", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
